### ISSUE TITLE
Using Cups Messenger iOS app with non-Embassy node

### ISSUE THREAD

**Issue by davidcaseria** [Start9Labs/cups-messenger#5]
I'm trying to connect to a my cups messenger server instance running on a non-embassy node using the Cups Messenger iOS app. After entering in my tor hidden service address and password that is configured in `/var/opt/cups/start9/config.yaml` I receive an error message stating "Server not found".

I am able to query the hidden service via curl and Tor browser using the Tor socks5 proxy so I believe everything is configured correctly server side. Is there something else required by the iOS app to connect to my running instance?

**Comment by dr-bonez** [comment]
as long as the cups container is running and the torrc is set up to route tcp traffic for both port 80 and 59001, it should work. try `curl`ing <toraddr>/api.  you should receive a 200 with 24 bytes indicating the version (3 big-endian unsigned 64bit integers)

**Comment by davidcaseria** [comment]
Yes, `curl`ing works:
```
$ curl --socks5-hostname localhost:9150 -u "me:<password>" "http://<hidden service address>.onion:59001/api" | xxd
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    24  100    24    0     0     18      0  0:00:01  0:00:01 --:--:--    18
00000000: 0000 0000 0000 0000 0000 0000 0000 0003  ................
00000010: 0000 0000 0000 0001                      ........
```

But the Cups app still gives a "Server not found" error message.

**Comment by dr-bonez** [comment]
please run the following command and let me know the status code:
```
curl --socks5-hostname localhost:9150 -u "me:<password>" "http://<hidden service address>.onion:59001/api?type=login"
```
